launchtask:
   podmonitorinterval: 10000
   timeout: 500000
   composehttptimeout: 300
   pullretry: 3
   maxretry: 3
plugins:
   pluginorder: splityaml,general,genesis
cleanpod:
   unhealthy: true
   cleanimageonmesoskill: true
   cleanvolumeandcontaineronmesoskill: true
dockerdump:
    enable: true
    path: /home/ubuntu
dockercomposeverbose: true