launchtask:
   podmonitorinterval: 10000
   pullretry: 3
   maxretry: 3
   timeout: 500000
disabledockerhealthcheck: true
plugins:
   pluginorder: general
cleanpod:
   unhealthy: true
   cleanvolumeandcontaineronmesoskill: true
   cleanimageonmesoskill: true